export const SELECTED_LANGUAGE = 'SELECTED_LANGUAGE'
export const SET_BOOLEAN_CHAIN_PAGE_CORRECT = 'SET_BOOLEAN_CHAIN_PAGE_CORRECT'
export const SET_BUSY_SEATS = 'SET_BUSY_SEATS'
export const SET_INDEX_SELECTED_SEAT= 'SET_INDEX_SELECTED_SEAT'
export const SET_LOGIN= 'SET_LOGIN'
export const SET_BAGAGE= 'SET_BAGAGE'



